name: Sync to Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    uses: spacemit-robotics/.github/.github/workflows/sync-to-gitee.yml@main
    with:
      branch: main
      gitee_org: spacemit-robotics
    secrets: inherit
